workflows:
  ios-app:
    name: Bommes Dashboard iOS
    instance_type: mac_mini_m1
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Dependencies
        script: npm install
      - name: Sync iOS (Updates Workspace)
        script: npx cap sync ios
      - name: Compile iOS App
        script: |
          cd ios/App
          xcodebuild build -workspace App.xcworkspace -scheme App -destination "generic/platform=iOS" CODE_SIGNING_ALLOWED=NO